### ISSUE TITLE
the macOS quickaction (i.e. "service" or "workflow") doesn't work in some Apple apps under Mojave

### ISSUE THREAD

**Issue by r-xue** [r-xue/ads2bibdesk#8]
The list at least includes Safari and AppleNote. 
Chrome seems to be fine. This was caused by macOS's sandboxing and the new Privacy feature.

related to https://github.com/jonathansick/ads_bibdesk/issues/74

**Comment by agallenne** [comment]
I just updated the OS from Sierra to Catalina and It does not work either.

**Comment by r-xue** [comment]
I haven't found any simple solution at this moment and probably won't get fixed in the near future. The CLI seems to work fine under Catalina.

**Comment by mr91i** [comment]
I guess, this is because Safari is not allowed to operates Applications (maybe). I am now using ads2bibdesk via CLI in Mojave, as seen below. To be honest, this is not a smart solution, but I hope it help someone. 
1. First, I made a simple script "ads2bibdesk.command" as,  
`~/.local/bin/ads2bibdesk "`pbpaste`"`
where pbpaste is a command which pastes the current clip board to the place, and please use proper path of ads2bibdesk. 
2. I enroll this script to my dock to use it easier.

Usage: When I find a reference which I want to download, I copy Bibcode/arxiv number/DOI and then click the script enrolled in my dock. After that, ads2bibdesk works like as in CLI.

**Comment by r-xue** [comment]
@mr91i Thanks for the suggestion! The original [ads_bibdesk](https://github.com/jonathansick/ads_bibdesk) had something like this (clipboard + app-click) implemented, but I entirely forgot about it. 

I just added the Automator-based app option back (with an updated README.rst). It seems to work properly under Catalina. The "app" method only uses the clipboard and the CLI program, so there is no "service" call need from Safari to BibDesk, which newer macOS doesn't allow any more.
